# Generated by Django 5.0.4 on 2024-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='live_location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
